version: "3.8"

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/develop/Dockerfile
    image: exams-api
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 500M
    expose:
      - 8000
    volumes:
      - ./:/app
    environment:
      - DJANGO_SETTINGS_MODULE=base.settings.develop
    tty: true
    stdin_open: true
    command: ["/start"]

  haproxy:
    image: haproxy:2.6-alpine
    container_name: haproxy
    restart: always
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - 8000:8080
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
